"""Run LLM inference for a prompt JSON generated by build_llm_prompt.py."""

from __future__ import annotations

import argparse
import base64
import copy
import io
import json
import logging
import os
from pathlib import Path
from typing import Any
from urllib.error import HTTPError, URLError
from urllib.parse import urlparse
from urllib.request import Request, urlopen

from commonsense_repro.extraction.fetch_github_issues_to_md import load_default_env

try:
    from PIL import Image
except ImportError:  # pragma: no cover - optional runtime dependency
    Image = None


DEFAULT_LOG_FILE = Path("data/logs/run_llm_inference.log")
DEFAULT_TIMEOUT = 120
DEFAULT_IMAGE_DOWNLOAD_TIMEOUT = 30
DEFAULT_MAX_IMAGE_BYTES = 7 * 1024 * 1024
SAFE_IMAGE_SUFFIXES = (".png", ".jpg", ".jpeg", ".webp", ".gif", ".bmp")
MULTIMODAL_FALLBACK_MARKERS = (
    "Download multimodal file timed out",
    "Failed to download multimodal content",
    "The provided URL does not appear to be valid",
    "The image format is illegal and cannot be opened",
    "Missing Content-Length of multimodal url",
    "convert_request_failed",
    "failed to download file",
    "status code: 429",
)


def setup_logger(log_file: Path) -> logging.Logger:
    log_file.parent.mkdir(parents=True, exist_ok=True)

    logger = logging.getLogger("run_llm_inference")
    logger.setLevel(logging.INFO)
    logger.handlers.clear()
    logger.propagate = False

    handler = logging.FileHandler(log_file, encoding="utf-8")
    handler.setFormatter(logging.Formatter("%(asctime)s %(levelname)s %(message)s"))
    logger.addHandler(handler)
    return logger


def load_json(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as file:
        data = json.load(file)

    if not isinstance(data, dict):
        raise ValueError(f"Expected a JSON object in {path}")

    return data


def resolve_endpoint(base_url: str) -> str:
    clean_url = base_url.rstrip("/")
    if clean_url.endswith("/chat/completions"):
        return clean_url
    return f"{clean_url}/chat/completions"


def call_chat_completions(
    *,
    endpoint: str,
    api_key: str,
    payload: dict[str, Any],
    timeout: int,
) -> dict[str, Any]:
    request_body = json.dumps(payload, ensure_ascii=False).encode("utf-8")
    request = Request(
        endpoint,
        data=request_body,
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
            "Accept": "application/json",
        },
        method="POST",
    )

    with urlopen(request, timeout=timeout) as response:
        body = response.read().decode("utf-8")
        return json.loads(body)


def extract_assistant_content(response: dict[str, Any]) -> str:
    choices = response.get("choices") or []
    if not choices:
        return ""

    message = choices[0].get("message") or {}
    content = message.get("content")

    if isinstance(content, str):
        return content
    if isinstance(content, list):
        text_parts = [
            item.get("text", "")
            for item in content
            if isinstance(item, dict) and item.get("text")
        ]
        return "\n".join(text_parts)
    return ""


def is_multimodal_download_error(error_body: str) -> bool:
    return any(marker in error_body for marker in MULTIMODAL_FALLBACK_MARKERS)


def iter_image_urls(messages: list[dict[str, Any]]) -> list[str]:
    urls: list[str] = []
    for message in messages:
        content = message.get("content")
        if not isinstance(content, list):
            continue
        for item in content:
            if not isinstance(item, dict) or item.get("type") != "image_url":
                continue
            image_url = item.get("image_url")
            if isinstance(image_url, dict) and isinstance(image_url.get("url"), str):
                urls.append(image_url["url"])
    return urls


def has_image_content(messages: list[dict[str, Any]]) -> bool:
    return bool(iter_image_urls(messages))


def should_prelocalize_image_url(url: str) -> bool:
    parsed = urlparse(url)
    if parsed.scheme.lower() != "https":
        return True

    path = parsed.path.lower()
    if any(path.endswith(suffix) for suffix in SAFE_IMAGE_SUFFIXES):
        return False
    if "github.com/user-attachments/assets/" in url:
        return False
    if parsed.netloc.lower() == "user-images.githubusercontent.com":
        return False
    return True


def should_prelocalize_messages(messages: list[dict[str, Any]]) -> bool:
    return any(should_prelocalize_image_url(url) for url in iter_image_urls(messages))


def download_image_bytes(url: str, timeout: int, max_bytes: int) -> bytes:
    request = Request(
        url,
        headers={
            "User-Agent": "commonsense-llm-inference/1.0",
            "Accept": "image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8",
        },
        method="GET",
    )

    with urlopen(request, timeout=timeout) as response:
        content_length = response.headers.get("Content-Length")
        if content_length and int(content_length) > max_bytes:
            raise ValueError(f"Image is too large: {content_length} bytes from {url}")

        chunks: list[bytes] = []
        total = 0
        while True:
            chunk = response.read(1024 * 256)
            if not chunk:
                break
            total += len(chunk)
            if total > max_bytes:
                raise ValueError(f"Image is too large: more than {max_bytes} bytes from {url}")
            chunks.append(chunk)

    return b"".join(chunks)


def image_bytes_to_data_url(image_bytes: bytes) -> str:
    if Image is None:
        encoded = base64.b64encode(image_bytes).decode("ascii")
        return f"data:image/png;base64,{encoded}"

    with Image.open(io.BytesIO(image_bytes)) as image:
        image.seek(0)
        if image.mode not in {"RGB", "RGBA"}:
            image = image.convert("RGBA")

        output = io.BytesIO()
        image.save(output, format="PNG")

    encoded = base64.b64encode(output.getvalue()).decode("ascii")
    return f"data:image/png;base64,{encoded}"


def localize_image_content(
    messages: list[dict[str, Any]],
    *,
    timeout: int,
    max_bytes: int,
) -> tuple[list[dict[str, Any]], list[str], list[str]]:
    localized_messages = copy.deepcopy(messages)
    localized_urls: list[str] = []
    failed_urls: list[str] = []

    for message in localized_messages:
        content = message.get("content")
        if not isinstance(content, list):
            continue
        retained_content: list[Any] = []
        for item in content:
            if not isinstance(item, dict) or item.get("type") != "image_url":
                retained_content.append(item)
                continue
            image_url = item.get("image_url")
            if not isinstance(image_url, dict) or not isinstance(image_url.get("url"), str):
                retained_content.append(item)
                continue

            original_url = image_url["url"]
            if original_url.startswith("data:"):
                retained_content.append(item)
                continue

            try:
                image_bytes = download_image_bytes(original_url, timeout, max_bytes)
                image_url["url"] = image_bytes_to_data_url(image_bytes)
                localized_urls.append(original_url)
                retained_content.append(item)
            except Exception:
                failed_urls.append(original_url)
        message["content"] = retained_content

    return localized_messages, localized_urls, failed_urls


def remove_image_content(messages: list[dict[str, Any]]) -> list[dict[str, Any]]:
    text_only_messages: list[dict[str, Any]] = []
    for message in messages:
        copied = dict(message)
        content = copied.get("content")
        if isinstance(content, list):
            copied["content"] = [
                item
                for item in content
                if not (
                    isinstance(item, dict)
                    and item.get("type") in {"image_url", "image", "video"}
                )
            ]
        text_only_messages.append(copied)
    return text_only_messages


def write_text(path: Path, text: str, overwrite: bool) -> None:
    if path.exists() and not overwrite:
        raise FileExistsError(f"{path} already exists. Use --overwrite to replace it.")

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def write_json(path: Path, data: Any, overwrite: bool) -> None:
    if path.exists() and not overwrite:
        raise FileExistsError(f"{path} already exists. Use --overwrite to replace it.")

    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as file:
        json.dump(data, file, ensure_ascii=False, indent=2)
        file.write("\n")


def build_request_payload(
    *,
    model: str,
    messages: list[dict[str, Any]],
    temperature: float,
    max_tokens: int | None,
) -> dict[str, Any]:
    payload: dict[str, Any] = {
        "model": model,
        "messages": messages,
        "temperature": temperature,
    }
    if max_tokens is not None:
        payload["max_tokens"] = max_tokens
    return payload


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Run LLM inference for a prompt JSON file."
    )
    parser.add_argument("--input", type=Path, required=True, help="Prompt JSON file.")
    parser.add_argument("--output-json", type=Path, required=True)
    parser.add_argument("--output-md", type=Path, required=True)
    parser.add_argument("--model", default=None, help="Override MODEL from .env.")
    parser.add_argument("--base-url", default=None, help="Override DASHSCOPE_URL from .env.")
    parser.add_argument("--temperature", type=float, default=0.0)
    parser.add_argument("--max-tokens", type=int, default=None)
    parser.add_argument("--timeout", type=int, default=DEFAULT_TIMEOUT)
    parser.add_argument(
        "--localize-images",
        action="store_true",
        help="Download image URLs locally and send them as base64 data URLs.",
    )
    parser.add_argument(
        "--image-download-timeout",
        type=int,
        default=DEFAULT_IMAGE_DOWNLOAD_TIMEOUT,
        help="Timeout in seconds for downloading each image when localizing images.",
    )
    parser.add_argument(
        "--max-image-bytes",
        type=int,
        default=DEFAULT_MAX_IMAGE_BYTES,
        help="Maximum bytes allowed for each downloaded image.",
    )
    parser.add_argument(
        "--no-text-only-fallback",
        action="store_true",
        help="Disable text-only retry when multimodal files cannot be downloaded.",
    )
    parser.add_argument("--overwrite", action="store_true")
    parser.add_argument("--log-file", type=Path, default=DEFAULT_LOG_FILE)
    args = parser.parse_args()

    load_default_env()
    logger = setup_logger(args.log_file)

    prompt_payload = load_json(args.input)
    messages = prompt_payload.get("messages")
    if not isinstance(messages, list):
        raise ValueError(f"Expected 'messages' list in {args.input}")

    api_key = os.environ.get("DASHSCOPE_API_KEY")
    base_url = args.base_url or os.environ.get("DASHSCOPE_URL")
    model = args.model or os.environ.get("MODEL")

    if not api_key:
        raise ValueError("DASHSCOPE_API_KEY is not configured.")
    if not base_url:
        raise ValueError("DASHSCOPE_URL is not configured.")
    if not model:
        raise ValueError("MODEL is not configured.")

    endpoint = resolve_endpoint(base_url)
    fallback_used = False
    fallback_mode = None
    multimodal_error_body = None
    localized_image_urls: list[str] = []
    failed_localized_image_urls: list[str] = []
    original_messages = messages
    image_input_mode = "url"

    if iter_image_urls(messages) and (args.localize_images or should_prelocalize_messages(messages)):
        messages, localized_image_urls, failed_localized_image_urls = localize_image_content(
            messages,
            timeout=args.image_download_timeout,
            max_bytes=args.max_image_bytes,
        )
        if has_image_content(messages):
            image_input_mode = "localized"
        else:
            fallback_used = True
            fallback_mode = "text_only"
            image_input_mode = "text_only"
        logger.info(
            "Localized images before inference input=%s localized_image_count=%s failed_image_count=%s image_input_mode=%s",
            args.input,
            len(localized_image_urls),
            len(failed_localized_image_urls),
            image_input_mode,
        )
        if failed_localized_image_urls:
            logger.warning(
                "Dropped invalid images before inference input=%s failed_urls=%s",
                args.input,
                failed_localized_image_urls,
            )

    request_payload = build_request_payload(
        model=model,
        messages=messages,
        temperature=args.temperature,
        max_tokens=args.max_tokens,
    )

    logger.info(
        "Start inference input=%s output_json=%s output_md=%s model=%s endpoint=%s image_count=%s timeout=%s",
        args.input,
        args.output_json,
        args.output_md,
        model,
        endpoint,
        prompt_payload.get("image_count"),
        args.timeout,
    )

    try:
        try:
            response = call_chat_completions(
                endpoint=endpoint,
                api_key=api_key,
                payload=request_payload,
                timeout=args.timeout,
            )
        except HTTPError as error:
            body = error.read().decode("utf-8", errors="replace")
            if (
                not args.no_text_only_fallback
                and prompt_payload.get("image_urls")
                and is_multimodal_download_error(body)
            ):
                multimodal_error_body = body
                if image_input_mode != "localized":
                    try:
                        messages, localized_image_urls, failed_localized_image_urls = localize_image_content(
                            original_messages,
                            timeout=args.image_download_timeout,
                            max_bytes=args.max_image_bytes,
                        )
                        fallback_used = True
                        if has_image_content(messages):
                            image_input_mode = "localized"
                            fallback_mode = "localized_images"
                        else:
                            image_input_mode = "text_only"
                            fallback_mode = "text_only"
                        logger.warning(
                            "Multimodal request failed; retrying with filtered images input=%s body=%s localized_image_count=%s failed_image_count=%s image_input_mode=%s",
                            args.input,
                            body,
                            len(localized_image_urls),
                            len(failed_localized_image_urls),
                            image_input_mode,
                        )
                        if failed_localized_image_urls:
                            logger.warning(
                                "Dropped invalid images during retry input=%s failed_urls=%s",
                                args.input,
                                failed_localized_image_urls,
                            )
                        request_payload = build_request_payload(
                            model=model,
                            messages=messages,
                            temperature=args.temperature,
                            max_tokens=args.max_tokens,
                        )
                        response = call_chat_completions(
                            endpoint=endpoint,
                            api_key=api_key,
                            payload=request_payload,
                            timeout=args.timeout,
                        )
                    except Exception as localize_error:
                        logger.warning(
                            "Localized image retry unavailable input=%s error=%s",
                            args.input,
                            localize_error,
                        )
                        messages = remove_image_content(original_messages)
                        image_input_mode = "text_only"
                        fallback_used = True
                        fallback_mode = "text_only"
                        request_payload = build_request_payload(
                            model=model,
                            messages=messages,
                            temperature=args.temperature,
                            max_tokens=args.max_tokens,
                        )
                        response = call_chat_completions(
                            endpoint=endpoint,
                            api_key=api_key,
                            payload=request_payload,
                            timeout=args.timeout,
                        )
                else:
                    fallback_used = True
                    fallback_mode = "text_only"
                    logger.warning(
                        "Localized multimodal request failed; retrying text-only input=%s body=%s",
                        args.input,
                        body,
                    )
                    messages = remove_image_content(original_messages)
                    image_input_mode = "text_only"
                    request_payload = build_request_payload(
                        model=model,
                        messages=messages,
                        temperature=args.temperature,
                        max_tokens=args.max_tokens,
                    )
                    response = call_chat_completions(
                        endpoint=endpoint,
                        api_key=api_key,
                        payload=request_payload,
                        timeout=args.timeout,
                    )
            else:
                logger.exception("HTTP error status=%s body=%s", error.code, body)
                raise

        assistant_content = extract_assistant_content(response)
        result = {
            "input_prompt_file": str(args.input),
            "model": model,
            "source_file": prompt_payload.get("source_file"),
            "template_file": prompt_payload.get("template_file"),
            "task": prompt_payload.get("task"),
            "image_urls": prompt_payload.get("image_urls", []),
            "request": {
                "model": model,
                "temperature": args.temperature,
                "max_tokens": args.max_tokens,
                "messages": messages,
            },
            "response": response,
            "assistant_content": assistant_content,
            "usage": response.get("usage"),
            "fallback_used": fallback_used,
            "fallback_mode": fallback_mode,
            "image_input_mode": image_input_mode,
            "localized_image_urls": localized_image_urls,
            "failed_localized_image_urls": failed_localized_image_urls,
            "multimodal_error_body": multimodal_error_body,
        }

        write_json(args.output_json, result, args.overwrite)
        write_text(args.output_md, assistant_content.strip() + "\n", args.overwrite)
        logger.info(
            "Inference succeeded output_json=%s output_md=%s usage=%s",
            args.output_json,
            args.output_md,
            response.get("usage"),
        )
        print(f"Wrote {args.output_json} and {args.output_md}. Log: {args.log_file}")
    except HTTPError:
        raise
    except (URLError, TimeoutError, json.JSONDecodeError, ValueError) as error:
        logger.exception("Inference failed error=%s", error)
        raise


if __name__ == "__main__":
    main()

